include: package:very_good_analysis/analysis_options.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    # We can also silence some if needed, but disabling them via linter rules is cleaner.
    todo: ignore

linter:
  rules:
    public_member_api_docs: false
    lines_longer_than_80_chars: false